const creatorsData = [
  {
    id: 1,
    name: "Jaydon Bothman",
    avatar: "/icons/Keepitreal.png",
    change: "+1.41%",
    nftsSold: 602,
    volume: "12.4 ETH",
  },
  {
    id: 2,
    name: "Ruben Carder",
    avatar: "/icons/Digilab.png",
    change: "+2.15%",
    nftsSold: 489,
    volume: "9.8 ETH",
  },
  {
    id: 3,
    name: "Alfredo Septimus",
    avatar: "/icons/gravityone.png",
    change: "+0.75%",
    nftsSold: 721,
    volume: "14.1 ETH",
  },
  {
    id: 4,
    name: "Davis Franci",
    avatar: "/icons/juani.png",
    change: "+3.42%",
    nftsSold: 610,
    volume: "11.2 ETH",
  },
  {
    id: 5,
    name: "Livia Rosser",
    avatar: "/icons/blue.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 6,
    name: "Kianna Donin",
    avatar: "/icons/fox.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 7,
    name: "Phillip Lipshutz",
    avatar: "/icons/Asian-man.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 8,
    name: "Maria Rossen",
    avatar: "/icons/robotica.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 9,
    name: "Kianna Stanton",
    avatar: "/icons/rusty.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 10,
    name: "Angel Lubin",
    avatar: "/icons/Nebulakid.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 11,
    name: "Allison Torff",
    avatar: "/icons/Allison.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 12,
    name: "Davis Workman",
    avatar: "/icons/robot.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 13,
    name: "Lindsey Lipshutz",
    avatar: "/icons/puppy.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 14,
    name: "Randy Carder",
    avatar: "/icons/Animakid.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 15,
    name: "Lydia Culhane",
    avatar: "/icons/dotku.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 16,
    name: "Rayna Bator",
    avatar: "/icons/MoonDancer.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 17,
    name: "Jucelyn Westervelt",
    avatar: "/icons/ghibler.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 18,
    name: "Marilyn Torff",
    avatar: "/icons/Keepitreal.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 19,
    name: "Skylar Levin",
    avatar: "/icons/Nebulakid.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
  {
    id: 20,
    name: "Terry Dorwart",
    avatar: "/icons/gravityone.png",
    change: "+1.25%",
    nftsSold: 456,
    volume: "8.5 ETH",
  },
];

export default creatorsData;
